name: robust_weighting
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.7.1
  - appdirs=1.4.3
  - attrs=19.1.0
  - backcall=0.1.0
  - black=19.3b0
  - blas=1.0
  - bleach=3.1.0
  - c-ares=1.15.0
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - cffi=1.12.3
  - cudatoolkit=10.0.130
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - gmp=6.1.2
  - graphite2=1.3.13
  - grpcio=1.16.1
  - harfbuzz=2.4.0
  - icu=64.2
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.6.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - jupyterlab=1.0.4
  - jupyterlab_server=1.0.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4=2.2.1
  - lz4-c=1.8.3
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mpfr=4.0.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - nodejs=10.13.0
  - notebook=5.7.8
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1d
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - pcre=8.43
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - pixman=0.38.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pybind11=2.2.4
  - pycparser=2.19
  - pygments=2.4.2
  - pyrsistent=0.14.11
  - python=3.7.3
  - python-dateutil=2.8.0
  - pyzmq=18.0.0
  - readline=7.0
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.14.0
  - terminado=0.8.2
  - testpath=0.4.2
  - texlive-core=20180414
  - tk=8.6.8
  - toml=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - argh==0.26.2
    - atomicwrites==1.3.0
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - configparser==4.0.2
    - crc32c==1.7
    - cvxopt==1.2.3
    - cvxpy==1.0.25
    - cycler==0.10.0
    - cython==0.29.10
    - dill==0.3.1.1
    - docker-pycreds==0.4.0
    - ecos==2.0.7.post1
    - filelock==3.0.12
    - flatbuffers==1.11
    - funcsigs==1.0.2
    - future==0.17.1
    - gitdb2==2.0.6
    - gitpython==3.0.5
    - gql==0.1.0
    - graphql-core==2.2.1
    - greenlet==0.4.15
    - idna==2.8
    - importlib-metadata==0.19
    - ipywidgets==7.5.1
    - joblib==0.13.2
    - jupyter==1.0.0
    - jupyter-console==6.1.0
    - jupyterlab-code-formatter==0.3.0
    - kiwisolver==1.1.0
    - matplotlib==3.1.0
    - modin==0.5.4
    - more-itertools==7.2.0
    - msgpack==0.6.2
    - multiprocess==0.70.9
    - neovim==0.3.1
    - nvidia-ml-py3==7.352.0
    - osqp==0.6.1
    - packaging==19.1
    - pandas==0.24.2
    - pathtools==0.1.2
    - plotly==4.5.0
    - pluggy==0.12.0
    - promise==2.2.1
    - protobuf==3.9.0
    - psutil==5.6.7
    - pudb==2019.2
    - py==1.8.0
    - pynvim==0.4.1
    - pyparsing==2.4.0
    - pytest==5.0.1
    - pytz==2019.1
    - pyyaml==5.1.1
    - qtconsole==4.7.1
    - qtpy==1.9.0
    - ray==0.7.1
    - redis==3.3.6
    - requests==2.22.0
    - retrying==1.3.3
    - rx==1.6.1
    - scikit-learn==0.22.2
    - scs==2.1.1-2
    - seaborn==0.9.0
    - sentry-sdk==0.13.5
    - shortuuid==0.5.0
    - sklearn==0.0
    - smmap2==2.0.5
    - subprocess32==3.5.4
    - tensorboardx==1.8
    - toolz==0.10.0
    - torch==1.4.0
    - torchtext==0.3.1
    - torchvision==0.4.0
    - tqdm==4.43.0
    - typing==3.7.4
    - urllib3==1.25.3
    - urwid==2.1.0
    - wandb==0.8.19
    - watchdog==0.9.0
    - widgetsnbextension==3.5.1
    - yapf==0.28.0
    - zipp==0.5.2

